config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  get 'about', to: 'static_pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :update, :edit] do
    member do
      post :request_friendship
      post :accept_friendship
      post :remove_friendship
    end
    get :friends
  end

  resources :notifications, only: [:destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :update, :destroy]
  # Defines the root path route ("/")
  root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true

  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :requests
  has_many :inbound_requests, class_name: 'Request', foreign_key: "friend_id"
  has_many :notifications
  
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :likeable, source_type: 'Post'
  has_many :liked_comments, through: :likes, source: :likeable, source_type: 'Comment'

  def full_name
    "#{first_name} #{last_name}"
  end

  def friends
    friends_array = requests.map { |request| request.friend_id if request.confirmed }
    friends_array += inbound_requests.map { |request| request.user.id if request.confirmed }
    friends_array.compact
  end

  def outbound_requests
    requests.map { |request| request.friend_id unless request.confirmed }.compact
  end

  def received_requests
    inbound_requests.map { |request| request.user.id unless request.confirmed }
  end

  def send_invitation(user)
    requests.create(friend_id: user.id) unless self == user || Request.exists?(self.id, user.id)
    user.notifications.build({ title: "#{self.full_name} has added you as a friend!", notif_type: "invite", link: "/users/#{self.id}" }).save
  end

  def accept_invitation(cuser, user)
    request = Request.find_by(user_id: user.id, friend_id: self.id)
    request.confirmed = true
    request.save
    cuser.notifications.find_by(link: "/users/#{user.id}").destroy
    user.notifications.build({ title: "#{self.full_name} has accepted your friend request!", notif_type: "accept", link: "/users/#{self.id}" }).save
  end

  def remove_friendship(cuser, user)
    request = Request.find(user.id, self.id)
    if(cuser.notifications.find_by(link: "/users/#{user.id}"))
      cuser.notifications.find_by(link: "/users/#{user.id}").destroy
    end
    request.destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  def index
    # all users listed here with friend options (request, accept, remove)
    @users = User.all
    @received = User.where(id: current_user.received_requests)
    @friends = User.where(id: current_user.friends)
    @sent_requests = User.where(id: current_user.outbound_requests)
  end

  def show
  end

  def edit
  end
  
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity}
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def friends
    # Lists all user friends
    @user = User.find(params[:user_id])
    @friends = User.where(id: @user.friends)
  end

  def request_friendship
    current_user.send_invitation(User.find(params[:id]))
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'Friend request sent.' }
      format.json { head :no_content }
    end
  end

  def accept_friendship
    current_user.accept_invitation(current_user, User.find(params[:id]))
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'Friend request accepted.' }
      format.json { head :no_content }
    end
  end

  def remove_friendship
    current_user.remove_friendship(current_user, User.find(params[:id]))
    respond_to do |format|
      format.html { redirect_back fallback_location: users_path, alert: 'Friend removed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :bio, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friends.html.erb
<div class="request-grid">
  <% @friends.each do |user| %>
    <% if user != @user %>
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <!-- add procedural grabber when gravatar -->
                <img src="https://static.thenounproject.com/png/574704-200.png" alt="Placeholder Avatar">
              </figure>
            </div>
            <div class="media-content">
              <p class="title is-4"><%= user.full_name %></p>
              <p class="subtitle is-6"><%= link_to "Profile", user_path(user) %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/_my_friends.html.erb
<div class="request-grid">
  <% @friends.each do |user| %>
    <% if user != current_user %>
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <!-- add procedural grabber when gravatar -->
                <img src="https://static.thenounproject.com/png/574704-200.png" alt="Placeholder Avatar">
              </figure>
            </div>
            <div class="media-content">
              <p class="title is-4"><%= user.full_name %></p>
              <p class="subtitle is-6"><%= link_to "Profile", user_path(user) %></p>
            </div>
          </div>
          <footer class="card-footer">
            <%= button_to "Remove Friend", remove_friendship_user_path(user), class: "button is-danger" %>
          </footer>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/_profile_drop.html.erb
<div class="dropdown">
  <span class="icon">
  </span>
  <span>
    <p><b><%= current_user.full_name%></b></p>
  </span>
  <span class="icon is-small"></span>
</div>
<div class="dropdown-menu" id="dropdown-menu" role="menu">
  <div class="dropdown-content">
    <p class="dropdown-item"><%= link_to "Show Profile", user_path(current_user), class: "has-text-black" %></p>
    <p class="dropdown-item"><%= link_to "Account Settings", edit_user_registration_path, class: "has-text-black" %></p>
    <p class="dropdown-item"><%= link_to "Logout", destroy_user_session_path, class: "has-text-black", data: { turbo_method: :delete } %></p>
  </div>
</div>

app/views/users/_requests.html.erb
<div class="request-grid">
  <% @received.each do |user| %>
    <div class="card">
      <div class="card-content">
        <div class="media">
          <div class="media-left">
            <figure class="image is-48x48">
              <!-- add procedural grabber when gravatar -->
              <img src="https://static.thenounproject.com/png/574704-200.png" alt="Placeholder Avatar">
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-4"><%= user.full_name %></p>
            <p class="subtitle is-6"><%= link_to "Profile", user_path(user) %></p>
          </div>
        </div>
        <footer class="card-footer">
          <%= button_to "Accept Request", accept_friendship_user_path(user), class: "button is-success" %>
          <%= button_to "Decline Request", remove_friendship_user_path(user), class: "button is-danger" %>
        </footer>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_users.html.erb
<div class="request-grid">
  <% @users.each do |user| %>
    <% if user != current_user && !@received.include?(user) && !@friends.include?(user)%>
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <!-- add procedural grabber when gravatar -->
                <img src="https://static.thenounproject.com/png/574704-200.png" alt="Placeholder Avatar">
              </figure>
            </div>
            <div class="media-content">
              <p class="title is-4"><%= user.full_name %></p>
              <p class="subtitle is-6"><%= link_to "Profile", user_path(user) %></p>
            </div>
          </div>
          <footer class="card-footer">
            <% if @sent_requests.include?(user) %>
              <%= button_to "Cancel Request", remove_friendship_user_path(user), class: "button is-danger" %>
            <% else %>
              <%= button_to "Add Friend", request_friendship_user_path(user), class: "button is-info" %>
            <% end %>
          </footer>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-one-third">
        <h1 class="title">Change your Profile info</h1>
        <%= simple_form_for(@user) do |f| %>
          <%= f.error_notification %>

          <div class="field">
            <div class="control">
              <%= f.input :first_name,
                          label: "First Name",
                          wrapper: false,
                          required: true,
                          input_html: { class: "input", autocomplete: "first_name" },
                          label_html: { class: "label" } %>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <%= f.input :last_name,
                          label: "Last Name",
                          wrapper: false,
                          required: true,
                          input_html: { class: "input", autocomplete: "last_name" },
                          label_html: { class: "label" } %>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <%= f.input :bio,
                          label: "Bio",
                          wrapper: false,
                          required: false,
                          input_html: { class: "input", autocomplete: "bio" },
                          label_html: { class: "label" } %>
            </div>
          </div>
          <%= f.button :submit, "Change Profile Info", class: "button is-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/friends.html.erb
<section>
  <div class="columns is-centered">
    <div class="column is-two-thirds">
      <h1 class="title"><%= @user.full_name %>'s Friends</h1>
      <% if @friends.empty? %>
        <p><%= @user.full_name %> has no friends yet :(... Do you want to be their friend?</p>
      <% else %>
        <%= render 'friends' %>
      <% end %>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section>
  <div class="columns is-centered">
    <div class="column is-two-thirds">
      <h1 class="title">Friends</h1>
      <% if @friends.empty? %>
        <p>You have no friends yet... Maybe Odin wants to be your friend!</p>
      <% else %>
        <%= render 'my_friends' %>
      <% end %>
      <br>
      <h2 class="subtitle">Requests</h2>
      <% if @received.empty? %>
        <p>You have no friend requests.</p>
      <% else %>
        <%= render 'requests' %>
      <% end %>
      <br>
      <h2 class="subtitle">All Other Users</h2>
      <%= render 'users' %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section>
  <div class="columns is-centered">
    <div class="column is-two-thirds">
      <div class="level">
        <div class="level-left">
          <div class="level-item">
            <figure class="image is-128x128 ">
              <!-- add procedural grabber when gravatar -->
              <img src="https://static.thenounproject.com/png/574704-200.png" alt="Placeholder Avatar" class="is-rounded">
            </figure>
          </div>
          <div class="level-item">
            <h1 class="title"><%= @user.full_name %></h1>
          </div>
        </div>
        <div class="level-right">
          <% if current_user == @user %>
            <div class="level-item">
              <%= button_to "Edit Profile", edit_user_path(current_user), method: :get, class: "button is-info"%>
            </div>
          <% end %>
        </div>
      </div>
      <p><%= @user.bio.nil? ? "This user has no bio yet" : @user.bio%></p>
      <br>
      <h2 class="subtitle">Posts</h2>
      <p>User's Posts..</p>

      <hr>
      <%= link_to user_friends_path(@user) do %>
        <p><%= @user.full_name %>'s Friends</p>
      <% end %>
      <p><%= @user.full_name %>'s liked posts</p>
    </div>
    
  </div>
</section>