config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  get 'about', to: 'static_pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :update, :edit] do
    member do
      post :request_friendship
      post :accept_friendship
      post :remove_friendship
    end
    get :friends
  end

  resources :notifications, only: [:destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :update, :destroy]
  # Defines the root path route ("/")
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable
  has_many :likers, through: :likes, source: :user
  
  def post_notification
    author.friends.each do |friend|
      User.find(friend).notifications.build({ title: "#{author.full_name} has posted something!", notif_type: "post", link: "#{id}" }).save
    end
  end

  def update_notification
    author.friends.each do |friend|
      User.find(friend).notifications.build({ title: "#{author.full_name} has updated a post!", notif_type: "post", link: "#{id}" }).save
    end
  end

  def liked_by(user)
    Like.find_by(user_id: user.id, likeable_id: id, likeable_type: 'Post') ? true : false
  end

  def userLike(user)
    Like.find_by(user_id: user.id, likeable_id: id, likeable_type: 'Post')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /posts or /posts.json
  def index
    posts = current_user.friends.map { |friend| User.find(friend).posts }.flatten
    posts += current_user.posts
    posts.sort_by! &:created_at
    @posts = posts.reverse
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        @post.post_notification
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        @post.update_notification
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<div id="<%= dom_id comment %>" class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <%= image_tag "https://static.thenounproject.com/png/574704-200.png", alt: "Placeholder image" %>
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-6"><%= comment.author.full_name %></p>
      </div>
    </div>
    <div class="content">
      <%= comment.body %>
      <br>
      <p class="subtitle is-7">
        <time datetime="2016-1-1"><%= comment.created_at.strftime("%B %d, %Y") %></time>
      </p>
      <br>
      <% if comment.liked_by(current_user) %>
        <%= button_to like_path(comment.userLike(current_user)),  method: :delete, class: "button" do %>
          <span class="icon">
            <%= image_tag("heart.svg") %>
          </span>
          <span>Unlike</span>
        <% end %>
      <% else %>
        <%= button_to likes_path, params: {likeable_id: comment.id, likeable_type: 'Comment'}, method: :post, class: "button" do %>
          <span class="icon">
            <%= image_tag("heart-outline.svg") %>
          </span>
          <span>Like</span>
        <% end %>
      <% end %>
    </div>
    <% if current_user == comment.author %>
      <footer class="card-footer">
        <%= link_to "Delete", comment_path(comment), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "card-footer-item" %>
      </footer>
    <% end %>
  </div>
</div>

app/views/posts/_comment_form.html.erb
<%= simple_form_for(comment) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :body, label: "What do you have to say?", input_html: { class: "textarea"}, wrapper: false, label_html: {class: "label"}, required: true %>
  </div>
</div>
<%= f.input :post_id, as: :hidden, input_html: {value: @post.id}, wrapper: false%>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/posts/_feed.html.erb
<div class="column is-half">
  <% @posts.each do |post| %>
    <%= link_to post_path(post) do %>
      <%= render 'post', post: post %>
    <% end %>  
      <footer class="card-footer">
        <% if post.liked_by(current_user) %>
          <%= button_to like_path(post.userLike(current_user)),  method: :delete, class: "button card-footer-item" do %>
            <span class="icon">
              <%= image_tag("heart.svg") %>
            </span>
            <span>Unlike</span>
          <% end %>
        <% else %>
          <%= button_to likes_path, params: {likeable_id: post.id, likeable_type: 'Post'}, method: :post, class: "button card-footer-item" do %>
            <span class="icon">
              <%= image_tag("heart-outline.svg") %>
            </span>
            <span> Like</span>
          <% end %>
        <% end %>
      </footer>
      </div>
      <br>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %> <!-- this will render the errors -->
  <h1 class="is-size-3"><strong>Text Post</strong></h1>
  <div class="field">
    <div class="control">
      <%= f.input :title,
                  label: "Title:",
                  input_html: { class: "input" },
                  wrapper: false,
                  label_html: { class: "label" },
                  placeholder: "Put in a fancy title!",
                  autofocus: true,
                  required: true %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.input :body,
                  label: "Body:",
                  input_html: { class: "textarea" },
                  wrapper: false,
                  label_html: { class: "label" },
                  placeholder: "Write your post here!",
                  required: true %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.button :submit, class: "button is-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>"class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <%= image_tag "https://static.thenounproject.com/png/574704-200.png", alt: "Placeholder image" %>
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4"><%= post.title %></p>
        <p class="subtitle is-6"><%= post.author.full_name %></p>
      </div>
    </div>
    <div class="content">
      <%= post.body %>
      <br>
      <p class="subtitle is-7">
        <time datetime="2016-1-1"><%= post.created_at.strftime("%B %d, %Y") %></time>
      </p>
    </div>
  </div>
  <footer class="card-footer">
    <% if current_page?(post_path(post)) %>
      <% if post.liked_by(current_user) %>
        <%= button_to like_path(post.userLike(current_user)),  method: :delete, class: "button card-footer-item" do %>
          <span class="icon">
            <%= image_tag("heart.svg") %>
          </span>
          <span>Unlike</span>
        <% end %>
      <% else %>
        <%= button_to likes_path, params: {likeable_id: post.id, likeable_type: 'Post'}, method: :post, class: "button card-footer-item" do %>
          <span class="icon">
            <%= image_tag("heart-outline.svg") %>
          </span>
          <span> Like</span>
        <% end %>
      <% end %>
      <% if current_user == post.author %>
        <a href="<%= edit_post_path(post) %>" class="card-footer-item">Edit</a>
        <a href="<%= post_path(post) %>" data-method="delete" class="card-footer-item">Delete</a>
      <% end %>
    <% end %>
  </footer>

app/views/posts/_sidebar.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Profile</p>
    <%= link_to user_path(current_user) do%>
      <div class="panel-block">
        <article class="media">
          <div class="media-left">
            <figure class="image is-64x64"><img src="https://static.thenounproject.com/png/574704-200.png" alt="You"></figure>
          </div>
          <div class="media-content">
            <div class="content">
              <p><strong><%= current_user.full_name %></strong></p>
            </div>
          </div>
        </article>
      </div>
    <% end %>
    <div class="panel-block">
      <div class="level is-mobile">
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Posts</p>
            <p class="title is-6"><%= current_user.posts.count %></p>
          </div>
        </div>
      </div>
    </div>
    
  </nav>
  <%= button_to "New Post", new_post_path(@post), class: "button is-info", method: :get %>
  
  <br>
  <%= link_to "Friendlist", users_path%>
  <p>Your Posts</p>
  <p>Your Liked Posts</p>
</div>

app/views/posts/edit.html.erb
<div class="section" >
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <%= link_to @post, class: "is-size-7" do%>
          <b>Back to Post</b>
        <% end %>
        <%= render "form", post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="section">
  <div class="columns">
    <%= render 'sidebar' %>
    <%= render 'feed' %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="section" >
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <%= link_to posts_path, class: "is-size-7" do%>
          <b>Back to Timeline</b>
        <% end %>
        <%= render "form", post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="section">
  <div class="columns">
    <%= render 'sidebar' %>
    <div class="column is-half">
      <%= link_to posts_path, class: "is-size-7" do%>
        <b>Back to Posts</b>
      <% end %>
      <%= render @post %>
      </div>
    <br>
    <!-- comment -->
    <%= render 'comment_form', comment: @comment %>
    <br>
    <% @comments.each do |comment| %>
      <%= render 'comment', comment: comment, post: @post %>
      <hr>
    <% end %>
  </div>
</div>