config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  get 'about', to: 'static_pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :update, :edit] do
    member do
      post :request_friendship
      post :accept_friendship
      post :remove_friendship
    end
    get :friends
  end

  resources :notifications, only: [:destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :update, :destroy]
  # Defines the root path route ("/")
  root "posts#index"
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="content has-text-centered"><p><strong>YAFC</strong>, a basic recreation of <a href="https://www.facebook.com">FaceBook</a>. Made by <a href="https://github.com/NotAtec">Jeroen Brinkhorst</a></p></div>
</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <div class="navbar-brand">
    <div class="navbar-burger">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>
  <div class="navbar-menu">
    <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
        <h1 id="top-left-title" class="title">YAFC</h1>
      <% end %>
    </div>
    <div class="navbar-start">
      <div class="navbar-item">
        <p class="control"><u><%= link_to "About", about_path, class: "has-text-black" %></u></p>
      </div>
    </div>
    <div class="navbar-end">
      <% if user_signed_in? %>
        <div class="navbar-item">
          <div class="dropdown is-right" id="notif-dd">
            <div class="dropdown-trigger">
              <% if @notifications.empty? %>
                <span class="icon">
                  <%= image_tag("bell-ring-outline.svg") %>
                </span>
              <% else %>
                <span class="icon">
                  <%= image_tag("bell-ring.svg") %>
                </span>
              <% end %>
            </div>
            <div class="dropdown-menu" id="dropdown-menu" role="menu">
              <div class="dropdown-content">
                <% if @notifications.empty? %>
                  <p class="dropdown-item">You have no new notifications!</p>
                <% else %>
                  <%= render 'layouts/notifications' %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="navbar-item" id="dd">
          <%= render "users/profile_drop"%>
        </div>
      <% else %>
        <div class="navbar-item">
          <p class="control"><%= link_to "Login", new_user_session_path, class: "has-text-black" %></p>
        </div>
        <div class="navbar-item">
          <p class="control"><%= link_to "Sign Up", new_user_registration_path, class: "has-text-black" %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_notifications.html.erb
 <% @notifications.each do |n| %>
  <div class="box dropdown-item" style="width:max-content;">
    <div class="level">
      <div class="level-left pr-2">
        <span class="level-item icon is-small"><%= image_tag('bell-ring-outline.svg') %></span>
        <p class="level-item"><%= n.title %></p>
      </div>
      <span></span>
      <div class="level-right">
        <% case n.notif_type %>
        <% when "invite" %>
        <% user = n.get_object %>
        <%= button_to "Accept", accept_friendship_user_path(user), class: "button is-small is-success" %>
        <%= button_to "Decline", remove_friendship_user_path(user), class: "button is-small is-danger" %>
        <% when "post" %>
        <%= link_to "View Post", post_path(n.link), class: "button is-small is-info" %>
      <% else %>
      <% end %>
      <span>&nbsp;&nbsp;</span>
      <%= button_to "", notification_path(n), method: :delete, class: "delete is-small"%>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YAFC - Yet Another Facebook Clone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if flash[:notice] %>
  		<div class="notification is-primary global-notification">
  			<p class="notice"><%= notice %></p>
  		</div>
  	<% end %>
  	<% if flash[:alert] %>
  		<div class="notification is-danger global-notification">
  			<p class="alert"><%= alert %></p>
  		</div>
  	<% end %>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>